### ISSUE TITLE
logger能不能拆分出来

### ISSUE THREAD

**Issue by yanglilizhang** [FPhoenixCorneaE/Common#1]
感谢作者，工具类挺好的，日志库能不能独立出来，我不想引入这个日志库，已经有其他类似的日志库了

**Comment by FPhoenixCorneaE** [comment]
> 感谢作者，工具类挺好的，日志库能不能独立出来，我不想引入这个日志库，已经有其他类似的日志库了

v2.0.5拆分出来了。
